version: "3.9"

services:

  arch-kde:
    build:
      context: .
      network: host
    image: arch-kde
    container_name: arch-kde
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - SUBFOLDER=/
      - KEYBOARD=${KEYBOARD}
      - TITLE=Arch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ARCH_KDE_DIR}/config:/config
      - ${PERSONAL_PHOTOS_DIR}:/photos
      - ${SHARED_PHOTOS_DIR}:/shared
    ports:
      - 3000:3000
    shm_size: "1gb" #optional
    restart: unless-stopped

networks:
  default:
    name: ${PIHOLE_BRIDGE_NETWORK}
    external: true
